
-- Run this in your Supabase SQL Editor to create the transactions table

create table public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  bill_number text not null,
  customer_name text,
  customer_phone text,
  items jsonb not null, -- Stores the list of medicines bought
  subtotal numeric,
  discount numeric,
  gst_amount numeric,
  total_amount numeric not null,
  payment_method text, -- 'CASH', 'UPI', 'RAZORPAY'
  payment_status text default 'COMPLETED',
  transaction_id text -- UPI Ref or Razorpay ID
);

-- Enable RLS (Optional, but good practice)
alter table public.transactions enable row level security;

-- Policy to allow public insert (for this demo app)
create policy "Allow public insert"
on public.transactions
for insert
to anon
with check (true);

-- Policy to allow public select (to view history)
create policy "Allow public select"
on public.transactions
for select
to anon
using (true);
